#!/bin/bash
SECRET="${@}"
: ${SECRET:=`btsync --generate-secret`}

echo "Starting btsync with the following secret key: $SECRET"

echo "{
    \"device_name\": \"Sync Container\",
    \"listening_port\": 55555,          // 0 - randomize port
    \"storage_path\": \"/btsync/.sync\",
    \"check_for_updates\": false,       //Check for BTSync program updates
    \"use_upnp\": false,                // use UPnP for port mapping
    \"download_limit\": 0,
    \"upload_limit\": 0,
    \"shared_folders\": [
        {
            \"secret\": \"$SECRET\",
            \"dir\": \"$SYNC_DIR\",
            \"use_relay_server\": false,
            \"use_tracker\": false,
            \"use_dht\": false,
            \"search_lan\": true,
            \"use_sync_trash\": false
        }
    ]
}" > /btsync/btsync.conf

btsync --config /btsync/btsync.conf --nodaemon
